# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_GUI.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QMainWindow,
    QPushButton, QSizePolicy, QWidget)

from pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1010, 530)
        font = QFont()
        font.setFamilies([u"Arial"])
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(390, 5, 611, 186))
        font1 = QFont()
        font1.setFamilies([u"DB Adman X"])
        font1.setPointSize(17)
        font1.setBold(True)
        self.groupBox_4.setFont(font1)
        self.grECG = PlotWidget(self.groupBox_4)
        self.grECG.setObjectName(u"grECG")
        self.grECG.setGeometry(QRect(10, 35, 591, 136))
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(390, 195, 611, 186))
        self.groupBox_5.setFont(font1)
        self.grSpO2 = PlotWidget(self.groupBox_5)
        self.grSpO2.setObjectName(u"grSpO2")
        self.grSpO2.setGeometry(QRect(10, 35, 591, 136))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 315, 361, 206))
        self.groupBox.setFont(font1)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(15, 50, 56, 26))
        font2 = QFont()
        font2.setFamilies([u"DB Adman X"])
        font2.setPointSize(30)
        font2.setBold(True)
        self.label.setFont(font2)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 75, 36, 16))
        font3 = QFont()
        font3.setFamilies([u"DB Adman X"])
        font3.setPointSize(12)
        font3.setBold(True)
        self.label_2.setFont(font3)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(15, 105, 56, 26))
        self.label_4.setFont(font2)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 130, 36, 16))
        self.label_3.setFont(font3)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 185, 36, 16))
        self.label_5.setFont(font3)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(15, 160, 61, 26))
        font4 = QFont()
        font4.setFamilies([u"DB Adman X"])
        font4.setPointSize(25)
        font4.setBold(True)
        self.label_6.setFont(font4)
        self.lbl_SYS = QLabel(self.groupBox)
        self.lbl_SYS.setObjectName(u"lbl_SYS")
        self.lbl_SYS.setGeometry(QRect(75, 35, 101, 51))
        font5 = QFont()
        font5.setFamilies([u"DB Adman X"])
        font5.setPointSize(50)
        font5.setBold(True)
        self.lbl_SYS.setFont(font5)
        self.lbl_SYS.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_SYS.setAlignment(Qt.AlignCenter)
        self.lbl_DIA = QLabel(self.groupBox)
        self.lbl_DIA.setObjectName(u"lbl_DIA")
        self.lbl_DIA.setGeometry(QRect(75, 90, 101, 51))
        self.lbl_DIA.setFont(font5)
        self.lbl_DIA.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_DIA.setAlignment(Qt.AlignCenter)
        self.lbl_Pulse = QLabel(self.groupBox)
        self.lbl_Pulse.setObjectName(u"lbl_Pulse")
        self.lbl_Pulse.setGeometry(QRect(85, 145, 76, 51))
        font6 = QFont()
        font6.setFamilies([u"DB Adman X"])
        font6.setPointSize(35)
        font6.setBold(True)
        self.lbl_Pulse.setFont(font6)
        self.lbl_Pulse.setStyleSheet(u"color: rgb(7, 64, 128);")
        self.lbl_Pulse.setAlignment(Qt.AlignCenter)
        self.btn_StartBP = QPushButton(self.groupBox)
        self.btn_StartBP.setObjectName(u"btn_StartBP")
        self.btn_StartBP.setGeometry(QRect(225, 45, 113, 91))
        self.btn_StartBP.setFont(font6)
        self.btn_StartBP.setStyleSheet(u"background-color: rgb(16, 128, 64);\n"
"color: rgb(255, 255, 255);")
        self.btn_BP_Clear = QPushButton(self.groupBox)
        self.btn_BP_Clear.setObjectName(u"btn_BP_Clear")
        self.btn_BP_Clear.setGeometry(QRect(227, 150, 106, 32))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 100, 361, 81))
        self.groupBox_2.setFont(font1)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 35, 41, 21))
        font7 = QFont()
        font7.setFamilies([u"DB Adman X"])
        font7.setPointSize(15)
        font7.setBold(True)
        self.label_7.setFont(font7)
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 55, 46, 21))
        self.label_8.setFont(font7)
        self.lbl_user_name = QLabel(self.groupBox_2)
        self.lbl_user_name.setObjectName(u"lbl_user_name")
        self.lbl_user_name.setGeometry(QRect(50, 35, 156, 21))
        self.lbl_user_name.setFont(font7)
        self.lbl_user_ID = QLabel(self.groupBox_2)
        self.lbl_user_ID.setObjectName(u"lbl_user_ID")
        self.lbl_user_ID.setGeometry(QRect(50, 55, 136, 21))
        self.lbl_user_ID.setFont(font7)
        self.btn_user_set = QPushButton(self.groupBox_2)
        self.btn_user_set.setObjectName(u"btn_user_set")
        self.btn_user_set.setGeometry(QRect(245, 40, 101, 32))
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(20, 185, 191, 131))
        self.groupBox_6.setFont(font1)
        self.btn_Capture = QPushButton(self.groupBox_6)
        self.btn_Capture.setObjectName(u"btn_Capture")
        self.btn_Capture.setGeometry(QRect(10, 35, 171, 41))
        self.btn_Capture.setFont(font4)
        self.btn_Capture.setStyleSheet(u"background-color: rgb(16, 128, 64);\n"
"color: rgb(255, 255, 255);")
        self.btn_Upload = QPushButton(self.groupBox_6)
        self.btn_Upload.setObjectName(u"btn_Upload")
        self.btn_Upload.setGeometry(QRect(10, 80, 171, 41))
        self.btn_Upload.setFont(font4)
        self.btn_Upload.setStyleSheet(u"background-color: rgb(15, 128, 255);\n"
"color: rgb(255, 255, 255);")
        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(390, 385, 191, 136))
        self.groupBox_7.setFont(font1)
        self.lbl_ECG_Pulse = QLabel(self.groupBox_7)
        self.lbl_ECG_Pulse.setObjectName(u"lbl_ECG_Pulse")
        self.lbl_ECG_Pulse.setGeometry(QRect(10, 30, 171, 96))
        font8 = QFont()
        font8.setFamilies([u"DB Adman X"])
        font8.setPointSize(80)
        font8.setBold(True)
        self.lbl_ECG_Pulse.setFont(font8)
        self.lbl_ECG_Pulse.setStyleSheet(u"color: rgb(16, 128, 64);")
        self.lbl_ECG_Pulse.setAlignment(Qt.AlignCenter)
        self.groupBox_8 = QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(590, 385, 211, 136))
        self.groupBox_8.setFont(font1)
        self.lbl_SpO2 = QLabel(self.groupBox_8)
        self.lbl_SpO2.setObjectName(u"lbl_SpO2")
        self.lbl_SpO2.setGeometry(QRect(10, 30, 196, 96))
        self.lbl_SpO2.setFont(font8)
        self.lbl_SpO2.setStyleSheet(u"color: rgb(128, 0, 2);")
        self.lbl_SpO2.setAlignment(Qt.AlignCenter)
        self.lbl_time = QLabel(self.centralwidget)
        self.lbl_time.setObjectName(u"lbl_time")
        self.lbl_time.setGeometry(QRect(15, 5, 231, 66))
        font9 = QFont()
        font9.setFamilies([u"DB Adman X"])
        font9.setPointSize(70)
        font9.setBold(True)
        self.lbl_time.setFont(font9)
        self.lbl_time.setScaledContents(True)
        self.lbl_date = QLabel(self.centralwidget)
        self.lbl_date.setObjectName(u"lbl_date")
        self.lbl_date.setGeometry(QRect(20, 65, 166, 31))
        self.lbl_date.setFont(font2)
        self.groupBox_9 = QGroupBox(self.centralwidget)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(810, 385, 191, 136))
        self.groupBox_9.setFont(font1)
        self.lbl_PR = QLabel(self.groupBox_9)
        self.lbl_PR.setObjectName(u"lbl_PR")
        self.lbl_PR.setGeometry(QRect(5, 30, 181, 96))
        self.lbl_PR.setFont(font8)
        self.lbl_PR.setStyleSheet(u"color: rgb(128, 0, 128);")
        self.lbl_PR.setAlignment(Qt.AlignCenter)
        self.groupBox_10 = QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(220, 180, 161, 156))
        font10 = QFont()
        font10.setFamilies([u"DB Adman X"])
        font10.setPointSize(20)
        font10.setBold(True)
        self.groupBox_10.setFont(font10)
        self.lbl_ECG_Status = QLabel(self.groupBox_10)
        self.lbl_ECG_Status.setObjectName(u"lbl_ECG_Status")
        self.lbl_ECG_Status.setGeometry(QRect(95, 55, 56, 26))
        self.lbl_ECG_Status.setFont(font4)
        self.btn_SpO2_ON = QPushButton(self.groupBox_10)
        self.btn_SpO2_ON.setObjectName(u"btn_SpO2_ON")
        self.btn_SpO2_ON.setGeometry(QRect(15, 100, 71, 41))
        self.btn_SpO2_ON.setFont(font10)
        self.btn_SpO2_ON.setStyleSheet(u"background-color: rgb(128, 0, 128);\n"
"color: rgb(255, 255, 255);")
        self.btn_ECG_ON = QPushButton(self.groupBox_10)
        self.btn_ECG_ON.setObjectName(u"btn_ECG_ON")
        self.btn_ECG_ON.setGeometry(QRect(15, 45, 71, 41))
        self.btn_ECG_ON.setFont(font10)
        self.btn_ECG_ON.setStyleSheet(u"background-color: rgb(7, 64, 128);\n"
"color: rgb(255, 255, 255);")
        self.lbl_SpO2_Status = QLabel(self.groupBox_10)
        self.lbl_SpO2_Status.setObjectName(u"lbl_SpO2_Status")
        self.lbl_SpO2_Status.setGeometry(QRect(95, 110, 56, 26))
        self.lbl_SpO2_Status.setFont(font4)


        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"ECG", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"SpO2", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Blood Pressure Monitor", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"SYS", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"mmHg", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"DIA", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"mmHg", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"/min", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"PULSE", None))
        self.lbl_SYS.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_DIA.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_Pulse.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.btn_StartBP.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.btn_BP_Clear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"User Profile", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u0e0a\u0e37\u0e48\u0e2d :", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e2b\u0e31\u0e2a :", None))
        self.lbl_user_name.setText(QCoreApplication.translate("MainWindow", u"AAA", None))
        self.lbl_user_ID.setText(QCoreApplication.translate("MainWindow", u"AAA", None))
        self.btn_user_set.setText(QCoreApplication.translate("MainWindow", u"Set. Profile", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Config", None))
        self.btn_Capture.setText(QCoreApplication.translate("MainWindow", u"Capture", None))
        self.btn_Upload.setText(QCoreApplication.translate("MainWindow", u"Upload", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"ECG Pluse", None))
        self.lbl_ECG_Pulse.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"SpO2", None))
        self.lbl_SpO2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lbl_time.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.lbl_date.setText(QCoreApplication.translate("MainWindow", u"00-00-0000", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"PR bpm", None))
        self.lbl_PR.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Mesurement", None))
        self.lbl_ECG_Status.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.btn_SpO2_ON.setText(QCoreApplication.translate("MainWindow", u"SpO2", None))
        self.btn_ECG_ON.setText(QCoreApplication.translate("MainWindow", u"ECG", None))
        self.lbl_SpO2_Status.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
    # retranslateUi

